/**
 * Demo mode seed data — real-shaped Malindi-area singles.
 * Photos use randomuser.me portrait URLs (gendered, stable).
 * Coordinates are approximate area centroids with small offsets so the
 * "Singles Near You" feature works without exposing real addresses.
 */
const now = () => new Date().toISOString();
const hoursAgo = (h) => new Date(Date.now() - h * 36e5).toISOString();

export const SEED_PROFILES = [
  {
    uid: 'p_aisha',
    fullName: 'Aisha',
    gender: 'female',
    interestedIn: ['male'],
    dateOfBirth: '2001-05-14',
    area: 'malindi_town',
    bio: 'Beach lover, foodie and entrepreneur. Looking for someone genuine.',
    interests: ['beach', 'music', 'food', 'travel'],
    datingIntention: 'serious',
    photos: [
      'https://randomuser.me/api/portraits/women/44.jpg',
      'https://randomuser.me/api/portraits/women/68.jpg',
    ],
    verification: { status: 'verified', phone: true, email: true, selfie: true },
    lastActiveAt: hoursAgo(0),
    location: { lat: -3.2054, lng: 40.1136 },
    preferences: { minAge: 23, maxAge: 34 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_fatma',
    fullName: 'Fatma',
    gender: 'female',
    interestedIn: ['male'],
    dateOfBirth: '1999-03-02',
    area: 'shella',
    bio: 'Teacher, Quran lover and beach sunset chaser. Family means everything to me.',
    interests: ['beach', 'books', 'nature', 'church'],
    datingIntention: 'marriage',
    photos: ['https://randomuser.me/api/portraits/women/33.jpg'],
    verification: { status: 'verified', phone: true, email: false, selfie: true },
    lastActiveAt: hoursAgo(2),
    location: { lat: -3.312, lng: 40.108 },
    preferences: { minAge: 25, maxAge: 36 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_brenda',
    fullName: 'Brenda',
    gender: 'female',
    interestedIn: ['male', 'female'],
    dateOfBirth: '2003-07-21',
    area: 'malindi_town',
    bio: 'Just moved back to Malindi. I dance at every wedding and I make the best pilau.',
    interests: ['dancing', 'cooking', 'music', 'food'],
    datingIntention: 'dating',
    photos: ['https://randomuser.me/api/portraits/women/12.jpg'],
    verification: { status: 'pending', phone: true, email: false, selfie: false },
    lastActiveAt: hoursAgo(0),
    location: { lat: -3.228, lng: 40.126 },
    preferences: { minAge: 21, maxAge: 30 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_neema',
    fullName: 'Neema',
    gender: 'female',
    interestedIn: ['male'],
    dateOfBirth: '1997-11-30',
    area: 'kilifi',
    bio: 'Nurse in Kilifi. Calm, ambitious and always up for a good conversation.',
    interests: ['fitness', 'coffee', 'travel', 'books'],
    datingIntention: 'open',
    photos: ['https://randomuser.me/api/portraits/women/57.jpg'],
    verification: { status: 'verified', phone: true, email: true, selfie: false },
    lastActiveAt: hoursAgo(6),
    location: { lat: -3.628, lng: 39.856 },
    preferences: { minAge: 25, maxAge: 38 },
    role: 'user',
    plan: 'free',
    showLocation: false,
  },
  {
    uid: 'p_zawadi',
    fullName: 'Zawadi',
    gender: 'female',
    interestedIn: ['male'],
    dateOfBirth: '2000-02-17',
    area: 'watamu',
    bio: 'Marine conservation volunteer in Watamu. Swim, snorkel, repeat 🐠',
    interests: ['swimming', 'beach', 'nature', 'travel'],
    datingIntention: 'serious',
    photos: ['https://randomuser.me/api/portraits/women/25.jpg'],
    verification: { status: 'verified', phone: true, email: true, selfie: true },
    lastActiveAt: hoursAgo(1),
    location: { lat: -3.351, lng: 40.024 },
    preferences: { minAge: 24, maxAge: 33 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_halima',
    fullName: 'Halima',
    gender: 'female',
    interestedIn: ['male'],
    dateOfBirth: '1995-06-09',
    area: 'mambrui',
    bio: 'Mum of two, small business owner. Ready for something real when the time is right.',
    interests: ['business', 'food', 'music', 'church'],
    datingIntention: 'marriage',
    photos: ['https://randomuser.me/api/portraits/women/90.jpg'],
    verification: { status: 'unverified', phone: false, email: false, selfie: false },
    lastActiveAt: hoursAgo(20),
    location: { lat: -3.223, lng: 39.889 },
    preferences: { minAge: 28, maxAge: 42 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_mercy',
    fullName: 'Mercy',
    gender: 'female',
    interestedIn: ['male'],
    dateOfBirth: '2002-09-12',
    area: 'malindi_town',
    bio: 'University student. Coffee, books and long beach walks. Say hi if you read too!',
    interests: ['coffee', 'books', 'beach', 'movies'],
    datingIntention: 'friendship',
    photos: ['https://randomuser.me/api/portraits/women/5.jpg'],
    verification: { status: 'pending', phone: true, email: false, selfie: false },
    lastActiveAt: hoursAgo(3),
    location: { lat: -3.212, lng: 40.104 },
    preferences: { minAge: 20, maxAge: 29 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_brian',
    fullName: 'Brian',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '1998-01-25',
    area: 'malindi_town',
    bio: 'Fisherman turned tour guide. I know every hidden beach between Malindi and Shella.',
    interests: ['fishing', 'beach', 'football', 'music'],
    datingIntention: 'serious',
    photos: [
      'https://randomuser.me/api/portraits/men/32.jpg',
      'https://randomuser.me/api/portraits/men/45.jpg',
    ],
    verification: { status: 'verified', phone: true, email: true, selfie: true },
    lastActiveAt: hoursAgo(0),
    location: { lat: -3.223, lng: 40.121 },
    preferences: { minAge: 21, maxAge: 30 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_ali',
    fullName: 'Ali',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '1996-08-04',
    area: 'watamu',
    bio: 'Hotel chef in Watamu. I will cook for you better than any restaurant here.',
    interests: ['cooking', 'food', 'gym', 'travel'],
    datingIntention: 'dating',
    photos: ['https://randomuser.me/api/portraits/men/78.jpg'],
    verification: { status: 'verified', phone: true, email: false, selfie: true },
    lastActiveAt: hoursAgo(4),
    location: { lat: -3.362, lng: 40.014 },
    preferences: { minAge: 22, maxAge: 32 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_kevin',
    fullName: 'Kevin',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '2000-04-18',
    area: 'malindi_town',
    bio: 'Boda entrepreneur and part-time DJ. Life is short — let’s dance.',
    interests: ['dancing', 'music', 'football', 'business'],
    datingIntention: 'open',
    photos: ['https://randomuser.me/api/portraits/men/11.jpg'],
    verification: { status: 'unverified', phone: false, email: false, selfie: false },
    lastActiveAt: hoursAgo(0),
    location: { lat: -3.234, lng: 40.11 },
    preferences: { minAge: 20, maxAge: 30 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_juma',
    fullName: 'Juma',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '1992-12-01',
    area: 'kilifi',
    bio: 'Civil engineer. Kind, stable and done with games. Looking for a partner in life.',
    interests: ['business', 'coffee', 'nature', 'fitness'],
    datingIntention: 'marriage',
    photos: ['https://randomuser.me/api/portraits/men/52.jpg'],
    verification: { status: 'verified', phone: true, email: true, selfie: true },
    lastActiveAt: hoursAgo(8),
    location: { lat: -3.64, lng: 39.843 },
    preferences: { minAge: 24, maxAge: 34 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_sammy',
    fullName: 'Sammy',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '1999-10-27',
    area: 'shella',
    bio: 'Photographer chasing sunsets and stories. Beach bonfires are my love language.',
    interests: ['sunset', 'beach', 'art', 'travel'],
    datingIntention: 'serious',
    photos: ['https://randomuser.me/api/portraits/men/64.jpg'],
    verification: { status: 'pending', phone: true, email: false, selfie: false },
    lastActiveAt: hoursAgo(2),
    location: { lat: -3.305, lng: 40.115 },
    preferences: { minAge: 21, maxAge: 31 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_daniel',
    fullName: 'Daniel',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '1997-05-06',
    area: 'malindi_town',
    bio: 'Accountant, gym in the morning, church on Sunday. Looking for friendship first.',
    interests: ['fitness', 'church', 'books', 'coffee'],
    datingIntention: 'friendship',
    photos: ['https://randomuser.me/api/portraits/men/22.jpg'],
    verification: { status: 'verified', phone: true, email: true, selfie: false },
    lastActiveAt: hoursAgo(14),
    location: { lat: -3.209, lng: 40.13 },
    preferences: { minAge: 22, maxAge: 32 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_omar',
    fullName: 'Omar',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '1994-07-15',
    area: 'mambrui',
    bio: 'Sailor and community coach. Traditional values, modern mindset.',
    interests: ['fishing', 'football', 'nature', 'music'],
    datingIntention: 'dating',
    photos: ['https://randomuser.me/api/portraits/men/36.jpg'],
    verification: { status: 'verified', phone: true, email: false, selfie: true },
    lastActiveAt: hoursAgo(5),
    location: { lat: -3.214, lng: 39.875 },
    preferences: { minAge: 23, maxAge: 33 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_hawa',
    fullName: 'Hawa',
    gender: 'female',
    interestedIn: ['male'],
    dateOfBirth: '1998-08-13',
    area: 'casuarina',
    bio: 'Early morning swims at Casuarina and a soft spot for bad jokes.',
    interests: ['swimming', 'beach', 'nature', 'travel'],
    datingIntention: 'dating',
    photos: ['https://randomuser.me/api/portraits/women/65.jpg'],
    verification: { status: 'verified', phone: true, email: true, selfie: true },
    lastActiveAt: hoursAgo(1),
    location: { lat: -3.233, lng: 40.121 },
    preferences: { minAge: 23, maxAge: 33 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_salma',
    fullName: 'Salma',
    gender: 'female',
    interestedIn: ['male'],
    dateOfBirth: '2001-01-27',
    area: 'majengo',
    bio: 'Bookshop girl in Majengo. Quiet at first, funny once you know me.',
    interests: ['books', 'coffee', 'church', 'nature'],
    datingIntention: 'marriage',
    photos: ['https://randomuser.me/api/portraits/women/21.jpg'],
    verification: { status: 'verified', phone: true, email: false, selfie: true },
    lastActiveAt: hoursAgo(3),
    location: { lat: -3.218, lng: 40.111 },
    preferences: { minAge: 24, maxAge: 34 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_cynthia',
    fullName: 'Cynthia',
    gender: 'female',
    interestedIn: ['male', 'female'],
    dateOfBirth: '1996-05-19',
    area: 'malindi_town',
    bio: 'Small boutique owner downtown. Travel plans always in the making.',
    interests: ['business', 'travel', 'music', 'movies'],
    datingIntention: 'serious',
    photos: ['https://randomuser.me/api/portraits/women/47.jpg'],
    verification: { status: 'verified', phone: true, email: true, selfie: false },
    lastActiveAt: hoursAgo(0),
    location: { lat: -3.211, lng: 40.119 },
    preferences: { minAge: 25, maxAge: 36 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_faith',
    fullName: 'Faith',
    gender: 'female',
    interestedIn: ['female', 'male'],
    dateOfBirth: '2003-10-02',
    area: 'watamu',
    bio: 'Watamu girl, dance floor first, questions later.',
    interests: ['dancing', 'music', 'food', 'beach'],
    datingIntention: 'open',
    photos: ['https://randomuser.me/api/portraits/women/9.jpg'],
    verification: { status: 'pending', phone: true, email: false, selfie: false },
    lastActiveAt: hoursAgo(2),
    location: { lat: -3.356, lng: 40.019 },
    preferences: { minAge: 20, maxAge: 30 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_asha',
    fullName: 'Asha',
    gender: 'female',
    interestedIn: ['male'],
    dateOfBirth: '1994-03-15',
    area: 'mowlem',
    bio: 'Caterer in Mowlem. If you eat my pilau I will know it is love.',
    interests: ['cooking', 'food', 'business', 'church'],
    datingIntention: 'marriage',
    photos: ['https://randomuser.me/api/portraits/women/16.jpg'],
    verification: { status: 'verified', phone: true, email: true, selfie: true },
    lastActiveAt: hoursAgo(7),
    location: { lat: -3.251, lng: 40.101 },
    preferences: { minAge: 27, maxAge: 40 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_linet',
    fullName: 'Linet',
    gender: 'female',
    interestedIn: ['male'],
    dateOfBirth: '1999-11-08',
    area: 'shella',
    bio: 'Paints the Shella sunsets and writes about them afterwards.',
    interests: ['art', 'sunset', 'travel', 'books'],
    datingIntention: 'dating',
    photos: ['https://randomuser.me/api/portraits/women/31.jpg'],
    verification: { status: 'pending', phone: true, email: false, selfie: false },
    lastActiveAt: hoursAgo(4),
    location: { lat: -3.309, lng: 40.112 },
    preferences: { minAge: 22, maxAge: 32 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_hassan',
    fullName: 'Hassan',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '1997-02-11',
    area: 'ganda',
    bio: 'Netball coach in Ganda. Sunday football, Monday work, always honest.',
    interests: ['fishing', 'football', 'nature', 'music'],
    datingIntention: 'dating',
    photos: ['https://randomuser.me/api/portraits/men/41.jpg'],
    verification: { status: 'verified', phone: true, email: false, selfie: true },
    lastActiveAt: hoursAgo(1),
    location: { lat: -3.291, lng: 40.113 },
    preferences: { minAge: 21, maxAge: 31 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_david',
    fullName: 'David',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '1993-09-22',
    area: 'malindi_town',
    bio: 'Runs a small transport business. Steady, calm and always early.',
    interests: ['business', 'coffee', 'travel', 'gym'],
    datingIntention: 'serious',
    photos: ['https://randomuser.me/api/portraits/men/13.jpg'],
    verification: { status: 'verified', phone: true, email: true, selfie: true },
    lastActiveAt: hoursAgo(5),
    location: { lat: -3.216, lng: 40.126 },
    preferences: { minAge: 24, maxAge: 35 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_tom',
    fullName: 'Tom',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '2001-06-30',
    area: 'watamu',
    bio: 'Dive instructor in Watamu. I will teach you to breathe underwater.',
    interests: ['swimming', 'sunset', 'art', 'beach'],
    datingIntention: 'open',
    photos: ['https://randomuser.me/api/portraits/men/29.jpg'],
    verification: { status: 'pending', phone: true, email: false, selfie: false },
    lastActiveAt: hoursAgo(0),
    location: { lat: -3.349, lng: 40.028 },
    preferences: { minAge: 20, maxAge: 30 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_eric',
    fullName: 'Eric',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '1999-12-05',
    area: 'ngala',
    bio: 'Music producer working out of Ngala. Your favourite tune has my name on it.',
    interests: ['football', 'dancing', 'gym', 'music'],
    datingIntention: 'dating',
    photos: ['https://randomuser.me/api/portraits/men/60.jpg'],
    verification: { status: 'unverified', phone: false, email: false, selfie: false },
    lastActiveAt: hoursAgo(2),
    location: { lat: -3.241, lng: 40.131 },
    preferences: { minAge: 20, maxAge: 31 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_baraka',
    fullName: 'Baraka',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '1995-04-19',
    area: 'mnarani',
    bio: 'Boat builder at Mnarani. Patient hands, patient heart.',
    interests: ['nature', 'fishing', 'beach', 'sunset'],
    datingIntention: 'serious',
    photos: ['https://randomuser.me/api/portraits/men/54.jpg'],
    verification: { status: 'verified', phone: true, email: true, selfie: true },
    lastActiveAt: hoursAgo(6),
    location: { lat: -3.203, lng: 40.092 },
    preferences: { minAge: 23, maxAge: 34 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
  {
    uid: 'p_stephen',
    fullName: 'Stephen',
    gender: 'male',
    interestedIn: ['female'],
    dateOfBirth: '1996-07-08',
    area: 'kisumu_ndogo',
    bio: 'Chef who actually eats at home too. Movie nights are non-negotiable.',
    interests: ['cooking', 'food', 'coffee', 'movies'],
    datingIntention: 'friendship',
    photos: ['https://randomuser.me/api/portraits/men/66.jpg'],
    verification: { status: 'pending', phone: true, email: false, selfie: false },
    lastActiveAt: hoursAgo(9),
    location: { lat: -3.222, lng: 40.103 },
    preferences: { minAge: 22, maxAge: 32 },
    role: 'user',
    plan: 'free',
    showLocation: true,
  },
].map((p) => ({ ...p, createdAt: now(), boostedUntil: null, suspended: false }));

export const DEMO_ACCOUNTS = [
  {
    uid: 'demo_user',
    email: 'demo@malindisingles.app',
    password: 'demo1234',
    role: 'user',
    fullName: 'Alex',
    linkedProfile: 'p_alex',
  },
  {
    uid: 'admin_user',
    email: 'admin@malindisingles.app',
    password: 'admin1234',
    role: 'admin',
    fullName: 'Moderator',
    linkedProfile: null,
  },
];

/**
 * The signed-in demo user's own profile (Alex, 27, Malindi).
 * Created lazily when the demo account first signs in / registers.
 */
export const buildDemoUserProfile = (uid, overrides = {}) => ({
  uid,
  fullName: 'Alex',
  gender: 'male',
  interestedIn: ['female'],
  dateOfBirth: '1999-06-10',
  area: 'malindi_town',
  bio: 'Easy-going Malindi local. Coffee, football and good conversations.',
  interests: ['beach', 'football', 'coffee', 'music'],
  datingIntention: 'open',
  photos: ['https://randomuser.me/api/portraits/men/75.jpg'],
  verification: { status: 'unverified', phone: false, email: false, selfie: false },
  lastActiveAt: now(),
  location: { lat: -3.2167, lng: 40.1167 },
  preferences: { minAge: 21, maxAge: 34 },
  role: 'user',
  plan: 'free',
  showLocation: true,
  boostedUntil: null,
  suspended: false,
  createdAt: now(),
  ...overrides,
});

/**
 * Demo incoming likes — SEED_LIKES_* pick order matters.
 *
 * premiumService sorts incoming likes oldest-first and shows the free tier
 * the first three, so index 0..2 are the clearly visible likes and 3..7 are
 * the blurred ones that 💎 Malindi Gold unlocks (hidden likes are never
 * deleted, only redacted).
 */
export const SEED_LIKES_FEMALE = [
  'p_aisha',
  'p_salma',
  'p_hawa',
  'p_cynthia',
  'p_faith',
  'p_linet',
  'p_zawadi',
  'p_brenda',
];

export const SEED_LIKES_MALE = [
  'p_brian',
  'p_eric',
  'p_hassan',
  'p_tom',
  'p_kevin',
  'p_baraka',
  'p_juma',
  'p_sammy',
];

/** Back-compat alias — interest-based selection now lives in authService. */
export const SEED_LIKES_TO_NEW_USER = [...SEED_LIKES_FEMALE.slice(0, 4), ...SEED_LIKES_MALE.slice(0, 4)];
